"use client";

import { Button } from "@/components/ui/button";
import React, { useState } from "react";
import { activate2fa, disable2fa, get2faSecret } from "./actions";
import { toast } from "sonner";
import { QRCodeSVG } from "qrcode.react";
import {
    InputOTP,
    InputOTPGroup,
    InputOTPSeparator,
    InputOTPSlot,
} from "@/components/ui/input-otp";

type Props = {
    twoFactorActivated: boolean;
};

export default function TwoFactorAuthForm({ twoFactorActivated }: Props) {
    const [isActivated, setIsActivated] = useState(twoFactorActivated);
    const [step, setStep] = useState(1);
    const [code, setCode] = useState("");
    const [otp, setOtp] = useState("");

    const handleEnableClick = async () => {
        const response = await get2faSecret();

        if (response.error) {
            toast.error(response.message);
            return;
        }
        setStep(2);
        setCode(response.twoFactorSecret ?? "");
    };

    const handleOTPSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();

        const response = await activate2fa(otp);

        if (response?.error) {
            toast.error(response.message);
            return;
        }

        toast.success("Two-Factor Authentication activated successfully!");
        setIsActivated(true);
    };

    const handleDisable2faClick = async () => {
        await disable2fa();
        toast.success("Two-Factor Authentication disabled successfully!");
        setIsActivated(false);
    };

    return (
        <div>
            {!!isActivated && (
                <Button
                    className="mt-3"
                    variant="destructive"
                    onClick={handleDisable2faClick}
                >
                    Disable Two-Factor Authentication
                </Button>
            )}
            {!isActivated && (
                <div>
                    {step === 1 && (
                        <Button className="mt-3" onClick={handleEnableClick}>
                            Enable Two-Factor Authentication
                        </Button>
                    )}
                    {step === 2 && (
                        <div>
                            <p className="text-xs text-muted-foreground py-2">
                                Scan the QR code with your Google Authentication
                                app to activate Two-Factor Authentication.
                            </p>
                            <QRCodeSVG value={code} />
                            <div className="mt-2">
                                <Button
                                    className="w-full my-2"
                                    onClick={() => setStep(3)}
                                >
                                    I have scanned the QR code
                                </Button>
                                <Button
                                    className="w-full my-2"
                                    onClick={() => setStep(1)}
                                    variant="outline"
                                >
                                    Cancel
                                </Button>
                            </div>
                        </div>
                    )}
                    {step === 3 && (
                        <form
                            className="flex flex-col gap-2 mt-3"
                            onSubmit={handleOTPSubmit}
                        >
                            <p className="text-xs text-muted-foreground">
                                Please enter the code generated by your Google
                                Authentication app
                            </p>

                            <InputOTP
                                className="mt-3"
                                maxLength={6}
                                value={otp}
                                onChange={setOtp}
                            >
                                <InputOTPGroup>
                                    <InputOTPSlot index={0} />
                                    <InputOTPSlot index={1} />
                                    <InputOTPSlot index={2} />
                                </InputOTPGroup>
                                <InputOTPSeparator />
                                <InputOTPGroup>
                                    <InputOTPSlot index={3} />
                                    <InputOTPSlot index={4} />
                                    <InputOTPSlot index={5} />
                                </InputOTPGroup>
                            </InputOTP>

                            <div className="flex flex-col gap-2 mt-3">
                                <Button type="submit" disabled={otp.length < 6}>
                                    Submit and Activate
                                </Button>
                                <Button
                                    variant="outline"
                                    onClick={() => setStep(2)}
                                >
                                    Cancel
                                </Button>
                            </div>
                        </form>
                    )}
                </div>
            )}
        </div>
    );
}
